server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/instruction_builder
    username: root
    password: password
    driver-class-name: org.mariadb.jdbc.Driver

  threads:
    virtual:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect

  kafka:
    bootstrap-servers: localhost:9094

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      enable-auto-commit: false
      auto-offset-reset: earliest

    properties:
      spring:
        deserializer:
          key:
            delegate:
              class: org.apache.kafka.common.serialization.StringDeserializer
          value:
            delegate:
              class: org.springframework.kafka.support.serializer.JsonDeserializer
        json:
          trusted:
            packages: "*"
          remove:
            type:
              headers: false
          value:
            default:
              type: com.ruchira.murex.kafka.model.HAWKMurexBookingRecord
      # security.protocol: SSL
      # ssl:
      #   truststore:
      #     location: /path/to/kafka.client.truststore.jks
      #     password: your-truststore-password
      #     type: JKS

app:
  tps:
    fields:
      ignoreFields:
        - comment0
        - comment1
      includeFields:
        - outboundProduct
        - familyGrpType
        - traderId
        - sourceSystem
        - comment0
        - comment1
        - traceId
        - exchangeRateType
        - legIdentificationType
        - historicalExchangeRate


logging:
  level:
    org.springframework.jdbc.core: WARN
    #org.springframework.jdbc.core.JdbcTemplate: DEBUG
    #org.springframework.jdbc.core.StatementCreatorUtils: TRACE
    org.springframework.transaction: DEBUG