spring:
  application:
    name: data-service
  
  datasource:
    url: jdbc:mariadb://localhost:3306/instruction_builder
    username: root
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true

# Transformation Configuration
transformation:
  ref-trade:
    default-rate: 0.9
  decimal:
    scale: 6


# Logging Configuration
logging:
  level:
    com.ruchira.murex: INFO
    org.springframework.jdbc.core: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Management and Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized

# Custom Application Properties
app:
  transformation:
    strategies:
      enabled: true
      cache-size: 1000
    
  field-mapping:
    cache-enabled: true
    reflection-cache-size: 500
  
  processing:
    batch-size: 100
    max-retry-attempts: 3