CREATE TABLE stg_mrx_ext (
    txn_id               VARCHAR(100),
    mx_prod_cd           VARCHAR(50),
    deal_udf_pc_code     VARCHAR(100),
    ctpy_relnship        VARCHAR(100),
    ctpy                 VARCHAR(100),
    next_rollover_date   DATE,
    value_dte            DATE,
    maturity_dte         DATE,
    trans_dte            DATE,
    pymt_dte             DATE,
    actual_int_spread    DECIMAL(38,6),
    buy_trans_amt        DECIMAL(38,6),
    sell_trans_amt       DECIMAL(38,6),
    mtm_trans_amt        DECIMAL(38,6),
    curr_1               VARCHAR(10),
    curr_2               VARCHAR(10),
    cpty_loc_ctry        VARCHAR(50),
    instrument_code      VARCHAR(50),
    mrx_entity_id        VARCHAR(50),
    curr_biz_unit        VARCHAR(50),
    next_reprice_dte     DATE,
    deal_status          VARCHAR(50),
    mkt_op_last_dte      DATE,
    issuer_code          VARCHAR(50),
    exch_rate            DECIMAL(38,6),
    exch_traded_ind      CHAR(1),
    swap_leg_ind         CHAR(1),
    spot_forward         VARCHAR(50),
    deliverable          CHAR(1),
    issuer               VARCHAR(255),
    sales_person_id      VARCHAR(50),
    trading_portf        VARCHAR(100),
    mtm_curr             VARCHAR(10),
    orig_curr            VARCHAR(10),
    live_amt             DECIMAL(38,6),
    cancel_reissue_ind   CHAR(1),
    delta                DECIMAL(38,6),
    market_value         DECIMAL(38,6),
    bs_indicator         CHAR(1),
    dirty_price          DECIMAL(38,6),
    discountd_mkt_val    DECIMAL(38,6),
    discountd_mkt_val_ccy VARCHAR(10),
    pv_on_cg             DECIMAL(38,6),
    ext_ref              VARCHAR(100),
    nondisc_mv           DECIMAL(38,6),
    pv_effect            DECIMAL(38,6),
    last_calc_dte        DATE,
    nondisc_mv_d         DECIMAL(38,6),
    live_qty             DECIMAL(38,6),
    past_cash_cap        DECIMAL(38,6),
    upl                  DECIMAL(38,6),
    realize_pl_fut       DECIMAL(38,6),
    fwsw_points          DECIMAL(38,6),
    nom_l1_orig          DECIMAL(38,6),
    nom_l2_orig          DECIMAL(38,6),
    disc_npv_l1          DECIMAL(38,6),
    disc_npv_l2          DECIMAL(38,6),
    unreal_pl_l1         DECIMAL(38,6),
    unreal_pl_l2         DECIMAL(38,6),
    init_price           DECIMAL(38,6),
    pl                   DECIMAL(38,6),
    mkt_price            DECIMAL(38,6),
    mv_curr              VARCHAR(10),
    fix_date             DATE,
    ntdsg_portf          VARCHAR(100),
    comment0             VARCHAR(255),
    spot_rate            DECIMAL(38,6),
    comment1             VARCHAR(255),
    comment2             VARCHAR(255),
    unre_cap_gain        DECIMAL(38,6),
    live_amt2            DECIMAL(38,6),
    initial_qty          DECIMAL(38,6),
    deal_time            TIMESTAMP,
    market_spot_rate1    DECIMAL(38,6),
    market_spot_rate2    DECIMAL(38,6),
    contract             VARCHAR(100),
    typology_mx3         VARCHAR(50),
    deal_no              VARCHAR(50),
    orig_contract_ref    VARCHAR(100),
    legal_bu             VARCHAR(50),
    sales_margin_usd     DECIMAL(38,6),
    sales_margin_curr_usd DECIMAL(38,6),
    source_data_loc_cd   VARCHAR(50),
    product_code         VARCHAR(50),
    dl_businessdate      DATE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE h_stg_mrx_ext_dmc (
    txn_id VARCHAR(100),
    mx_prod_cd VARCHAR(100),
    deal_udf_pc_code VARCHAR(100),
    ctpy_relnship VARCHAR(100),
    ctpy VARCHAR(100),
    next_rollover_date DATE,
    value_dte DATE,
    maturity_dte DATE,
    trans_dte DATE,
    pymt_dte DATE,
    actual_int_spread DECIMAL(20,8),
    buy_trans_amt DECIMAL(20,8),
    sell_trans_amt DECIMAL(20,8),
    mtm_trans_amt DECIMAL(20,8),
    curr1 VARCHAR(20),
    curr2 VARCHAR(20),
    cpty_loc_ctry VARCHAR(50),
    instrument_code VARCHAR(100),
    mrx_entity_id VARCHAR(100),
    curr_biz_unit VARCHAR(100),
    next_reprice_dte DATE,
    deal_status VARCHAR(50),
    mkt_op_last_dte DATE,
    issuer_code VARCHAR(100),
    exch_rate DECIMAL(20,8),
    exch_traded_ind VARCHAR(10),
    swap_leg_ind VARCHAR(10),
    spot_forward VARCHAR(10),
    deliverable VARCHAR(10),
    issuer VARCHAR(100),
    sales_person_id VARCHAR(100),
    trading_portf VARCHAR(100),
    mtm_curr VARCHAR(20),
    orig_curr VARCHAR(20),
    live_amt DECIMAL(20,8),
    cancel_reissue_ind VARCHAR(10),
    delta DECIMAL(20,8),
    market_value DECIMAL(20,8),
    bs_indicator VARCHAR(10),
    dirty_price DECIMAL(20,8),
    discountd_mkt_val DECIMAL(20,8),
    discountd_mkt_val_ccy VARCHAR(20),
    pv_on_cg DECIMAL(20,8),
    ext_ref VARCHAR(100),
    nondisc_mv VARCHAR(100),
    pv_effect DECIMAL(20,8),
    last_calc_dte DATE,
    nondisc_mv_d VARCHAR(100),
    live_qty VARCHAR(100),
    past_cash_cap DECIMAL(20,8),
    upl DECIMAL(20,8),
    realize_pl_fut DECIMAL(20,8),
    fwsw_points DECIMAL(20,8),
    nom_l1_orig DECIMAL(20,8),
    nom_l2_orig DECIMAL(20,8),
    disc_npv_l1 DECIMAL(20,8),
    disc_npv_l2 DECIMAL(20,8),
    unreal_pl_l1 DECIMAL(20,8),
    unreal_pl_l2 DECIMAL(20,8),
    init_price DECIMAL(20,8),
    pl DECIMAL(20,8),
    mkt_price DECIMAL(20,8),
    mv_curr VARCHAR(20),
    fix_date DATE,
    ntdsg_portf VARCHAR(100),
    comment0 VARCHAR(255),
    spot_rate DECIMAL(20,8),
    comment1 VARCHAR(255),
    comment2 VARCHAR(255),
    unre_cap_gain DECIMAL(20,8),
    live_amt2 DECIMAL(20,8),
    initial_qty DECIMAL(20,8),
    deal_time TIMESTAMP,
    market_spot_rate1 DECIMAL(20,8),
    market_spot_rate2 DECIMAL(20,8),
    contract VARCHAR(100),
    typology_mx3 VARCHAR(100),
    deal_no VARCHAR(100),
    orig_contract_ref VARCHAR(100),
    legal_bu VARCHAR(100),
    sales_margin_usd DECIMAL(20,8),
    sales_margin_curr_usd VARCHAR(20),
    source_data_loc_cd VARCHAR(50),
    product_code VARCHAR(100),
    dl_businessdate DATE,
    historical_exchange_rate DECIMAL(20,8),
    trace_id VARCHAR(100),
    instruction_rule_id VARCHAR(100),
    murex_book_code VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE h_murex_booking (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    trade_reference VARCHAR(100) NOT NULL,
    trade_execution_date DATE NOT NULL,
    trade_execution_time DATETIME NOT NULL,
    deal_type VARCHAR(50),
    murex_short_label VARCHAR(100),
    source_portfolio VARCHAR(50),
    regional_portfolio VARCHAR(50),
    destination_portfolio VARCHAR(50),
    internal CHAR(1) DEFAULT 'Y',
    intermediary_portfolio VARCHAR(50),
    broker_label VARCHAR(100),
    split_cross CHAR(1),
    split_spot_swap CHAR(1),
    family_grp_type VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE h_murex_trade_leg (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    trade_id BIGINT NOT NULL,
    leg_type ENUM('NEAR','FAR') NOT NULL,
    deal_ccy VARCHAR(10),
    deal_amount DECIMAL(20,8),
    bs_indicator CHAR(1),
    client_forward_rate DECIMAL(20,8),
    client_spot_rate DECIMAL(20,8),
    init_price DECIMAL(20,8),
    client_rate DECIMAL(20,8),
    fwsw_points VARCHAR(20),
    sales_margin_amount DECIMAL(20,8),
    sales_margin_ccy VARCHAR(10),
    value_date DATE,
    fix_date DATE,
    execution_venue VARCHAR(100),
    source_system VARCHAR(50),
    broker VARCHAR(100),
    maker_or_taker VARCHAR(50),
    trader_id VARCHAR(50),
    orig_contract_ref VARCHAR(100),
    desk VARCHAR(50),
    counter_party_code VARCHAR(50),
    trade_leg_type VARCHAR(50),
    comment0 VARCHAR(255),
    comment1 VARCHAR(255),
    comment2 VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (trade_id) REFERENCES h_murex_booking(id) ON DELETE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE h_murex_trade_leg_component (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    trade_leg_id BIGINT NOT NULL,
    currency_pair VARCHAR(10),
    market_spot_rate DECIMAL(20,8),
    market_forward_rate DECIMAL(20,8),
    spot_value_date DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (trade_leg_id) REFERENCES h_murex_trade_leg(id) ON DELETE CASCADE
);
